### ISSUE TITLE
Mensajes de error | Registro mal dicho

### ISSUE THREAD

**Issue by GLideKS** [CarlosMasabet/Proyecto#1]
![imagen](https://user-images.githubusercontent.com/84994993/225169773-5a3b049d-e192-4250-9d21-25b70531e95a.png)
![imagen](https://user-images.githubusercontent.com/84994993/225169967-d0a2ae8b-5ba4-47dc-a9fd-ae75b5cd750f.png)

**Comment by CarlosMasabet** [comment]
fixed
